<a href="https://colab.research.google.com/github/sagarbhadra7/Algorithms/blob/master/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
%matplotlib inline

In [0]:
digits=load_digits()

In [13]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [14]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [7]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
digits.DESCR

".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 5620\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixel

In [12]:
digits.data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [0]:
df=pd.DataFrame(digits.data,digits.target)

In [20]:
df

0    1     2     3     4     5    6   ...   57   58    59    60    61   62   63
0   0.0  0.0   5.0  13.0   9.0   1.0  0.0  ...  0.0  6.0  13.0  10.0   0.0  0.0  0.0
1   0.0  0.0   0.0  12.0  13.0   5.0  0.0  ...  0.0  0.0  11.0  16.0  10.0  0.0  0.0
2   0.0  0.0   0.0   4.0  15.0  12.0  0.0  ...  0.0  0.0   3.0  11.0  16.0  9.0  0.0
3   0.0  0.0   7.0  15.0  13.0   1.0  0.0  ...  0.0  7.0  13.0  13.0   9.0  0.0  0.0
4   0.0  0.0   0.0   1.0  11.0   0.0  0.0  ...  0.0  0.0   2.0  16.0   4.0  0.0  0.0
..  ...  ...   ...   ...   ...   ...  ...  ...  ...  ...   ...   ...   ...  ...  ...
9   0.0  0.0   4.0  10.0  13.0   6.0  0.0  ...  0.0  2.0  14.0  15.0   9.0  0.0  0.0
0   0.0  0.0   6.0  16.0  13.0  11.0  1.0  ...  0.0  6.0  16.0  14.0   6.0  0.0  0.0
8   0.0  0.0   1.0  11.0  15.0   1.0  0.0  ...  0.0  2.0   9.0  13.0   6.0  0.0  0.0
9   0.0  0.0   2.0  10.0   7.0   0.0  0.0  ...  0.0  5.0  12.0  16.0  12.0  0.0  0.0
8   0.0  0.0  10.0  14.0   8.0   1.0  0.0  ...  1.0  8.0  12.0  14.0  12.0  1.0  0.0

[1797 rows x 64 columns]

In [0]:
df['target'] = digits.target


In [23]:
df.head()

0    1    2     3     4     5  ...    59    60    61   62   63  target
0  0.0  0.0  5.0  13.0   9.0   1.0  ...  13.0  10.0   0.0  0.0  0.0       0
1  0.0  0.0  0.0  12.0  13.0   5.0  ...  11.0  16.0  10.0  0.0  0.0       1
2  0.0  0.0  0.0   4.0  15.0  12.0  ...   3.0  11.0  16.0  9.0  0.0       2
3  0.0  0.0  7.0  15.0  13.0   1.0  ...  13.0  13.0   9.0  0.0  0.0       3
4  0.0  0.0  0.0   1.0  11.0   0.0  ...   2.0  16.0   4.0  0.0  0.0       4

[5 rows x 65 columns]

In [0]:
X = df.drop(['target'], axis='columns')
y = df.target

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [0]:
from sklearn.svm import SVC
model = SVC()

In [28]:
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [29]:
model.score(X_test, y_test)

0.9911111111111112

In [30]:
model_C = SVC(C=1)
model_C.fit(X_train, y_train)
model_C.score(X_test, y_test)

0.9911111111111112

In [37]:
model.predict(X_test)

array([3, 4, 6, 9, 5, 5, 8, 7, 8, 5, 2, 4, 0, 5, 2, 4, 1, 9, 4, 4, 9, 2,
       7, 9, 9, 3, 8, 9, 4, 1, 3, 1, 2, 1, 4, 1, 5, 6, 6, 2, 7, 7, 2, 9,
       1, 3, 3, 8, 0, 5, 1, 5, 1, 7, 9, 2, 9, 8, 3, 4, 9, 0, 2, 7, 5, 4,
       5, 0, 0, 7, 5, 0, 6, 4, 5, 3, 6, 9, 0, 4, 1, 6, 4, 7, 3, 8, 9, 4,
       5, 8, 2, 9, 6, 9, 8, 6, 6, 3, 8, 6, 8, 9, 6, 9, 8, 3, 0, 5, 2, 0,
       3, 8, 8, 7, 9, 6, 9, 1, 8, 8, 5, 1, 9, 3, 8, 1, 3, 0, 8, 1, 4, 7,
       2, 4, 2, 7, 2, 6, 6, 4, 7, 0, 2, 7, 6, 7, 6, 4, 2, 2, 7, 4, 8, 3,
       7, 2, 4, 4, 8, 6, 5, 1, 0, 1, 2, 3, 7, 8, 6, 7, 9, 4, 9, 9, 9, 3,
       7, 2, 7, 5, 7, 2, 6, 2, 6, 1, 2, 5, 1, 9, 8, 8, 0, 4, 9, 5, 2, 3,
       3, 0, 7, 1, 9, 5, 5, 0, 0, 8, 3, 9, 0, 5, 9, 9, 0, 3, 2, 7, 9, 3,
       9, 7, 6, 8, 2, 1, 9, 6, 4, 5, 8, 5, 6, 5, 6, 5, 6, 7, 6, 3, 4, 0,
       1, 9, 4, 2, 0, 5, 4, 8, 8, 9, 4, 3, 7, 2, 5, 5, 6, 0, 1, 9, 3, 7,
       1, 5, 7, 4, 2, 3, 0, 6, 5, 4, 8, 2, 7, 6, 8, 3, 8, 2, 3, 7, 1, 6,
       6, 4, 6, 5, 0, 5, 7, 9, 0, 7, 0, 5, 6, 1, 9,

In [43]:
linear_model = SVC(kernel='linear')
linear_model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [44]:
linear_model.score(X_test,y_test)

0.9711111111111111